### PR TITLE
Added base project files, also added the folder organization of the project and the example page

### LINKED ISSUE #3: Create base project in repository
Create the base project for the repository using MVVM Architecture.
### Acceptance Criteria

- [x] Project created and added on the repository
- [x] Folder organization has been created
- [x] An example page has been added

### Epic Link
[Pokemon List Epic](https://github.com/jmacboy/Pokedex-ios/wiki/Epic-for-Pokemon-list)

### PR DESCRIPTION
**Pull request by IrvingJVR-MX**
Added base project, folder organization and example page

### CODE REVIEW

**Comment by jmacboy** [comment]
Don't forget to assign the issue here on the side bar =======================>

Where it says:
Successfully merging this pull request may close these issues. @IrvingJVR-MX

**Comment by jmacboy** [comment]
Also add a descriptive title, more than the autogenerated one. For example you can add the PBI Title or the solution you made.

**Review by Rodrigo-Schar — COMMENTED** [review]
in case we are going to use pods, uncoment the pods folder in the gitignore

**Comment by IrvingJVR-MX** [comment]
@Rodrigo-Schar done :)

**Comment by IrvingJVR-MX** [comment]
@jmacboy done :)

**Review by Rodrigo-Schar — APPROVED** [review]

**Review by jmacboy — APPROVED** [review]

**Pull request merged**
